### ISSUE TITLE
[QUESTION] - Is it possible to decode a Share URL?

### ISSUE THREAD

**Issue by ebeale-cloudshare** [loilo/diffr#461]
Hello @loilo !

Firstly, I'd like to thank you for this awesome tool! I use it a lot and love it's simplicity and focus on privacy!

I'm wondering if it's possible to decode a Share URL to see the raw diff info?

IIUC, the raw diff is encoded using the lz-string npm package? Is it also base64 encoded?

Thanks!

**Comment by loilo** [comment]
Exactly, `lz-string` is used to encode the JSON-encoded state of the editor (content on the left, content on the right and settings). The [`util/encoding-worker/encoding-tools.ts`](https://github.com/loilo/diffr/blob/master/util/encoding-worker/encoding-tools.ts) file is the one responsible for that.

Or, if you prefer, here's a [quick codepen](https://codepen.io/loilo/pen/WNPmRdO?editors=1010) I threw together which does the job for you. I'm not sure what you're trying to do, but this should make pretty obvious how it's done.

**Comment by ebeale-cloudshare** [comment]
Hey thanks, @loilo !

I'm just trying to see the decoded output is all, so your response is perfect!

Thanks again!
